package com.guoche.teyvatdelight;

import com.guoche.teyvatdelight.registry.ModBlocks;
import com.guoche.teyvatdelight.registry.ModCreativeTabs;
import com.guoche.teyvatdelight.registry.ModDataComponents;
import com.guoche.teyvatdelight.registry.ModEntityTypes;
import com.guoche.teyvatdelight.registry.ModItems;
import com.guoche.teyvatdelight.registry.ModMenuTypes;
import com.guoche.teyvatdelight.registry.ModRegistries;
import com.guoche.teyvatdelight.registry.ModEvents;
import com.guoche.teyvatdelight.registry.ModVillage;
import com.guoche.teyvatdelight.registry.ModWorldgen;
import com.guoche.teyvatdelight.registry.food.BasicDishes;
import com.mojang.logging.LogUtils;
import net.minecraft.core.component.DataComponentType;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ai.village.poi.PoiType;
import net.minecraft.world.entity.npc.VillagerProfession;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemNameBlockItem;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.neoforged.bus.api.EventPriority;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.ModList;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import org.slf4j.Logger;
import vectorwing.farmersdelight.common.item.KnifeItem;

@Mod(TeyvatDelight.MODID)
public class TeyvatDelight {
    public static final String MODID = "teyvatdelight";
    public static final Logger LOGGER = LogUtils.getLogger();

    // Compatibility aliases retain the original public field names and types.
    // New content belongs in registry classes, not in this entrypoint.
    @Deprecated public static final DeferredRegister.DataComponents DATA_COMPONENT_TYPES = ModDataComponents.DATA_COMPONENT_TYPES;
    @Deprecated public static final DeferredRegister.Items ITEMS = ModItems.ITEMS;
    @Deprecated public static final DeferredRegister.Blocks BLOCKS = ModBlocks.BLOCKS;
    @Deprecated public static final DeferredRegister<Feature<?>> FEATURES = ModWorldgen.FEATURES;
    @Deprecated public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = ModCreativeTabs.CREATIVE_MODE_TABS;
    @Deprecated public static final DeferredRegister<EntityType<?>> ENTITIES = ModEntityTypes.ENTITIES;
    @Deprecated public static final DeferredRegister<MenuType<?>> MENUS = ModMenuTypes.MENUS;
    @Deprecated public static final DeferredRegister<PoiType> POI_TYPES = ModVillage.POI_TYPES;
    @Deprecated public static final DeferredRegister<VillagerProfession> VILLAGER_PROFESSIONS = ModVillage.VILLAGER_PROFESSIONS;
    @Deprecated public static final DeferredHolder<DataComponentType<?>, DataComponentType<Integer>> STARS = ModDataComponents.STARS;
    @Deprecated public static final DeferredHolder<DataComponentType<?>, DataComponentType<String>> FOOD_QUALITY = ModDataComponents.FOOD_QUALITY;
    @Deprecated public static final DeferredHolder<Feature<?>, Feature<WildTeyvatCropPatchConfiguration>> WILD_CROP_PATCH_FEATURE = ModWorldgen.WILD_CROP_PATCH_FEATURE;
    @Deprecated public static final DeferredHolder<Feature<?>, Feature<TeyvatMineralPatchConfiguration>> MINERAL_PATCH_FEATURE = ModWorldgen.MINERAL_PATCH_FEATURE;
    @Deprecated public static final DeferredHolder<EntityType<?>, EntityType<StarconchEntity>> STARCONCH = ModEntityTypes.STARCONCH;
    @Deprecated public static final DeferredHolder<EntityType<?>, EntityType<EmptyFeatherMothEntity>> EMPTY_FEATHER_MOTH = ModEntityTypes.EMPTY_FEATHER_MOTH;
    @Deprecated public static final DeferredHolder<EntityType<?>, EntityType<KatheryneEntity>> KATHERYNE = ModEntityTypes.KATHERYNE;
    @Deprecated public static final DeferredHolder<MenuType<?>, MenuType<KatheryneMenu>> KATHERYNE_MENU = ModMenuTypes.KATHERYNE_MENU;
    @Deprecated public static final DeferredBlock<Block> XUAN_CI_JADE_FIELD = ModBlocks.XUAN_CI_JADE_FIELD;
    @Deprecated public static final DeferredBlock<Block> NI_CI_ZHI_FIELD = ModBlocks.NI_CI_ZHI_FIELD;
    @Deprecated public static final DeferredBlock<Block> CHU_CI_ZHU_FIELD = ModBlocks.CHU_CI_ZHU_FIELD;
    @Deprecated public static final DeferredBlock<Block> XUAN_CI_PU_FIELD = ModBlocks.XUAN_CI_PU_FIELD;
    @Deprecated public static final DeferredBlock<Block> PRIMOGEM_BLOCK = ModBlocks.PRIMOGEM_BLOCK;
    @Deprecated public static final DeferredBlock<Block> MORA_BLOCK = ModBlocks.MORA_BLOCK;
    @Deprecated public static final DeferredBlock<ChenyuTeaBrewBlock> CHENYU_TEA_BREW_BLOCK = ModBlocks.CHENYU_TEA_BREW_BLOCK;
    @Deprecated public static final DeferredHolder<PoiType, PoiType> TEYVAT_MERCHANT_POI = ModVillage.TEYVAT_MERCHANT_POI;
    @Deprecated public static final DeferredHolder<VillagerProfession, VillagerProfession> TEYVAT_MERCHANT_PROFESSION = ModVillage.TEYVAT_MERCHANT_PROFESSION;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> BURIED_SHIPO_FRAGMENT = ModBlocks.BURIED_SHIPO_FRAGMENT;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> REPAIRING_SHIPO = ModBlocks.REPAIRING_SHIPO;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> INTACT_SHIPO = ModBlocks.INTACT_SHIPO;
    @Deprecated public static final DeferredBlock<NaturalShipoBlock> NATURAL_SHIPO = ModBlocks.NATURAL_SHIPO;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> BURIED_JINGHUAGUSUI_FRAGMENT = ModBlocks.BURIED_JINGHUAGUSUI_FRAGMENT;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> REPAIRING_JINGHUAGUSUI = ModBlocks.REPAIRING_JINGHUAGUSUI;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> INTACT_JINGHUAGUSUI = ModBlocks.INTACT_JINGHUAGUSUI;
    @Deprecated public static final DeferredBlock<NaturalJinghuagusuiBlock> NATURAL_JINGHUAGUSUI = ModBlocks.NATURAL_JINGHUAGUSUI;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> BURIED_YEBOSHI_FRAGMENT = ModBlocks.BURIED_YEBOSHI_FRAGMENT;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> REPAIRING_YEBOSHI = ModBlocks.REPAIRING_YEBOSHI;
    @Deprecated public static final DeferredBlock<ShipoCropBlock> INTACT_YEBOSHI = ModBlocks.INTACT_YEBOSHI;
    @Deprecated public static final DeferredBlock<NaturalNoctilucousJadeBlock> NATURAL_YEBOSHI = ModBlocks.NATURAL_YEBOSHI;
    @Deprecated public static final DeferredBlock<NaturalNoctilucousJadeBlock> NATURAL_DEEPSLATE_YEBOSHI = ModBlocks.NATURAL_DEEPSLATE_YEBOSHI;
    @Deprecated public static final DeferredBlock<SmallLampGrassCropBlock> SMALL_LAMP_GRASS_CROP = ModBlocks.SMALL_LAMP_GRASS_CROP;
    @Deprecated public static final DeferredBlock<WindwheelAsterCropBlock> WINDWHEEL_ASTER_CROP = ModBlocks.WINDWHEEL_ASTER_CROP;
    @Deprecated public static final DeferredBlock<CallaLilyCropBlock> CALLA_LILY_CROP = ModBlocks.CALLA_LILY_CROP;
    @Deprecated public static final DeferredBlock<MintCropBlock> MINT_CROP = ModBlocks.MINT_CROP;
    @Deprecated public static final DeferredBlock<WolfhookCropBlock> WOLFHOOK_CROP = ModBlocks.WOLFHOOK_CROP;
    @Deprecated public static final DeferredBlock<SnapdragonCropBlock> SNAPDRAGON_CROP = ModBlocks.SNAPDRAGON_CROP;
    @Deprecated public static final DeferredBlock<ValberryCropBlock> VALBERRY_CROP = ModBlocks.VALBERRY_CROP;
    @Deprecated public static final DeferredBlock<DandelionCropBlock> DANDELION_CROP = ModBlocks.DANDELION_CROP;
    @Deprecated public static final DeferredBlock<CeciliaCropBlock> CECILIA_CROP = ModBlocks.CECILIA_CROP;
    @Deprecated public static final DeferredBlock<RaspberryCropBlock> RASPBERRY_CROP = ModBlocks.RASPBERRY_CROP;
    @Deprecated public static final DeferredBlock<SweetFlowerCropBlock> SWEET_FLOWER_CROP = ModBlocks.SWEET_FLOWER_CROP;
    @Deprecated public static final DeferredBlock<WindblumeFlowerBlock> PINK_WINDBLUME = ModBlocks.PINK_WINDBLUME;
    @Deprecated public static final DeferredBlock<WindblumeFlowerBlock> YELLOW_WINDBLUME = ModBlocks.YELLOW_WINDBLUME;
    @Deprecated public static final DeferredBlock<WindblumeFlowerBlock> PURPLE_WINDBLUME = ModBlocks.PURPLE_WINDBLUME;
    @Deprecated public static final DeferredBlock<JueyunChiliCropBlock> JUEYUN_CHILI_CROP = ModBlocks.JUEYUN_CHILI_CROP;
    @Deprecated public static final DeferredBlock<GlazeLilyCropBlock> GLAZE_LILY_CROP = ModBlocks.GLAZE_LILY_CROP;
    @Deprecated public static final DeferredBlock<MufengMushroomCropBlock> MUFENG_MUSHROOM_CROP = ModBlocks.MUFENG_MUSHROOM_CROP;
    @Deprecated public static final DeferredBlock<SumeruRoseCropBlock> SUMERU_ROSE_CROP = ModBlocks.SUMERU_ROSE_CROP;
    @Deprecated public static final DeferredBlock<GrainfruitCropBlock> GRAINFRUIT_CROP = ModBlocks.GRAINFRUIT_CROP;
    @Deprecated public static final DeferredBlock<FluorescentFungusCropBlock> FLUORESCENT_FUNGUS_CROP = ModBlocks.FLUORESCENT_FUNGUS_CROP;
    @Deprecated public static final DeferredBlock<SeaGanodermaCropBlock> SEA_GANODERMA_CROP = ModBlocks.SEA_GANODERMA_CROP;
    @Deprecated public static final DeferredBlock<DendrobiumCropBlock> DENDROBIUM_CROP = ModBlocks.DENDROBIUM_CROP;
    @Deprecated public static final DeferredBlock<FrostlampFlowerCropBlock> FROSTLAMP_FLOWER_CROP = ModBlocks.FROSTLAMP_FLOWER_CROP;
    @Deprecated public static final DeferredBlock<GrowingCoralShellBlock> GROWING_CORAL_SHELL = ModBlocks.GROWING_CORAL_SHELL;
    @Deprecated public static final DeferredBlock<PearlBearingCoralShellBlock> PEARL_BEARING_CORAL_SHELL = ModBlocks.PEARL_BEARING_CORAL_SHELL;
    @Deprecated public static final DeferredBlock<NaturalCoralPearlBlock> NATURAL_CORAL_PEARL = ModBlocks.NATURAL_CORAL_PEARL;
    @Deprecated public static final DeferredBlock<HorsetailBottomBlock> HORSETAIL_BOTTOM = ModBlocks.HORSETAIL_BOTTOM;
    @Deprecated public static final DeferredBlock<HorsetailTopBlock> HORSETAIL_TOP = ModBlocks.HORSETAIL_TOP;
    @Deprecated public static final DeferredBlock<ThirstingJinxinFlowerBlock> THIRSTING_JINXIN_FLOWER = ModBlocks.THIRSTING_JINXIN_FLOWER;
    @Deprecated public static final DeferredBlock<BlazingJinxinFlowerBlock> BLAZING_JINXIN_FLOWER = ModBlocks.BLAZING_JINXIN_FLOWER;
    @Deprecated public static final DeferredBlock<BurntOutJinxinFlowerBlock> BURNT_OUT_JINXIN_FLOWER = ModBlocks.BURNT_OUT_JINXIN_FLOWER;
    @Deprecated public static final DeferredBlock<WildSmallLampGrassBlock> WILD_SMALL_LAMP_GRASS = ModBlocks.WILD_SMALL_LAMP_GRASS;
    @Deprecated public static final DeferredBlock<WildWindwheelAsterBlock> WILD_WINDWHEEL_ASTER = ModBlocks.WILD_WINDWHEEL_ASTER;
    @Deprecated public static final DeferredBlock<WildCallaLilyBlock> WILD_CALLA_LILY = ModBlocks.WILD_CALLA_LILY;
    @Deprecated public static final DeferredBlock<WildMintBlock> WILD_MINT = ModBlocks.WILD_MINT;
    @Deprecated public static final DeferredBlock<WildWolfhookBlock> WILD_WOLFHOOK = ModBlocks.WILD_WOLFHOOK;
    @Deprecated public static final DeferredBlock<WildSnapdragonBlock> WILD_SNAPDRAGON = ModBlocks.WILD_SNAPDRAGON;
    @Deprecated public static final DeferredBlock<WildValberryBlock> WILD_VALBERRY = ModBlocks.WILD_VALBERRY;
    @Deprecated public static final DeferredBlock<WildDandelionBlock> WILD_DANDELION = ModBlocks.WILD_DANDELION;
    @Deprecated public static final DeferredBlock<WildCeciliaBlock> WILD_CECILIA = ModBlocks.WILD_CECILIA;
    @Deprecated public static final DeferredBlock<WildRaspberryBlock> WILD_RASPBERRY = ModBlocks.WILD_RASPBERRY;
    @Deprecated public static final DeferredBlock<WildSweetFlowerBlock> WILD_SWEET_FLOWER = ModBlocks.WILD_SWEET_FLOWER;
    @Deprecated public static final DeferredBlock<WildJueyunChiliBlock> WILD_JUEYUN_CHILI = ModBlocks.WILD_JUEYUN_CHILI;
    @Deprecated public static final DeferredBlock<WildGlazeLilyBlock> WILD_GLAZE_LILY = ModBlocks.WILD_GLAZE_LILY;
    @Deprecated public static final DeferredBlock<WildMufengMushroomBlock> WILD_MUFENG_MUSHROOM = ModBlocks.WILD_MUFENG_MUSHROOM;
    @Deprecated public static final DeferredBlock<WildSumeruRoseBlock> WILD_SUMERU_ROSE = ModBlocks.WILD_SUMERU_ROSE;
    @Deprecated public static final DeferredBlock<WildGrainfruitBlock> WILD_GRAINFRUIT = ModBlocks.WILD_GRAINFRUIT;
    @Deprecated public static final DeferredBlock<WildHorsetailBlock> WILD_HORSETAIL = ModBlocks.WILD_HORSETAIL;
    @Deprecated public static final DeferredBlock<WildJinxinFlowerBlock> WILD_JINXIN_FLOWER = ModBlocks.WILD_JINXIN_FLOWER;
    @Deprecated public static final DeferredBlock<WildFluorescentFungusBlock> WILD_FLUORESCENT_FUNGUS = ModBlocks.WILD_FLUORESCENT_FUNGUS;
    @Deprecated public static final DeferredBlock<WildSeaGanodermaBlock> WILD_SEA_GANODERMA = ModBlocks.WILD_SEA_GANODERMA;
    @Deprecated public static final DeferredBlock<WildDendrobiumBlock> WILD_DENDROBIUM = ModBlocks.WILD_DENDROBIUM;
    @Deprecated public static final DeferredBlock<WildFrostlampFlowerBlock> WILD_FROSTLAMP_FLOWER = ModBlocks.WILD_FROSTLAMP_FLOWER;
    @Deprecated public static final DeferredItem<BlockItem> XUAN_CI_JADE_FIELD_ITEM = ModItems.XUAN_CI_JADE_FIELD_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> NI_CI_ZHI_FIELD_ITEM = ModItems.NI_CI_ZHI_FIELD_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> CHU_CI_ZHU_FIELD_ITEM = ModItems.CHU_CI_ZHU_FIELD_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> XUAN_CI_PU_FIELD_ITEM = ModItems.XUAN_CI_PU_FIELD_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> NATURAL_SHIPO_ITEM = ModItems.NATURAL_SHIPO_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> NATURAL_YEBOSHI_ITEM = ModItems.NATURAL_YEBOSHI_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> NATURAL_DEEPSLATE_YEBOSHI_ITEM = ModItems.NATURAL_DEEPSLATE_YEBOSHI_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> NATURAL_JINGHUAGUSUI_ITEM = ModItems.NATURAL_JINGHUAGUSUI_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_SMALL_LAMP_GRASS_ITEM = ModItems.WILD_SMALL_LAMP_GRASS_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_WINDWHEEL_ASTER_ITEM = ModItems.WILD_WINDWHEEL_ASTER_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_CALLA_LILY_ITEM = ModItems.WILD_CALLA_LILY_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_MINT_ITEM = ModItems.WILD_MINT_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_WOLFHOOK_ITEM = ModItems.WILD_WOLFHOOK_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_SNAPDRAGON_ITEM = ModItems.WILD_SNAPDRAGON_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_VALBERRY_ITEM = ModItems.WILD_VALBERRY_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_DANDELION_ITEM = ModItems.WILD_DANDELION_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_CECILIA_ITEM = ModItems.WILD_CECILIA_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_RASPBERRY_ITEM = ModItems.WILD_RASPBERRY_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_SWEET_FLOWER_ITEM = ModItems.WILD_SWEET_FLOWER_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> PINK_WINDBLUME_ITEM = ModItems.PINK_WINDBLUME_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> YELLOW_WINDBLUME_ITEM = ModItems.YELLOW_WINDBLUME_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> PURPLE_WINDBLUME_ITEM = ModItems.PURPLE_WINDBLUME_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_JUEYUN_CHILI_ITEM = ModItems.WILD_JUEYUN_CHILI_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_GLAZE_LILY_ITEM = ModItems.WILD_GLAZE_LILY_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_MUFENG_MUSHROOM_ITEM = ModItems.WILD_MUFENG_MUSHROOM_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_SUMERU_ROSE_ITEM = ModItems.WILD_SUMERU_ROSE_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_GRAINFRUIT_ITEM = ModItems.WILD_GRAINFRUIT_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_HORSETAIL_ITEM = ModItems.WILD_HORSETAIL_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_JINXIN_FLOWER_ITEM = ModItems.WILD_JINXIN_FLOWER_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_FLUORESCENT_FUNGUS_ITEM = ModItems.WILD_FLUORESCENT_FUNGUS_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_SEA_GANODERMA_ITEM = ModItems.WILD_SEA_GANODERMA_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_DENDROBIUM_ITEM = ModItems.WILD_DENDROBIUM_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> WILD_FROSTLAMP_FLOWER_ITEM = ModItems.WILD_FROSTLAMP_FLOWER_ITEM;
    @Deprecated public static final DeferredItem<Item> SMALL_LAMP_GRASS = ModItems.SMALL_LAMP_GRASS;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> SMALL_LAMP_GRASS_SEEDS = ModItems.SMALL_LAMP_GRASS_SEEDS;
    @Deprecated public static final DeferredItem<Item> WINDWHEEL_ASTER = ModItems.WINDWHEEL_ASTER;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> WINDWHEEL_ASTER_SEEDS = ModItems.WINDWHEEL_ASTER_SEEDS;
    @Deprecated public static final DeferredItem<Item> CALLA_LILY = ModItems.CALLA_LILY;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> CALLA_LILY_SEEDS = ModItems.CALLA_LILY_SEEDS;
    @Deprecated public static final DeferredItem<Item> MINT = ModItems.MINT;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> MINT_SEEDS = ModItems.MINT_SEEDS;
    @Deprecated public static final DeferredItem<Item> WINDBLUME = ModItems.WINDBLUME;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> WOLFHOOK = ModItems.WOLFHOOK;
    @Deprecated public static final DeferredItem<Item> SNAPDRAGON = ModItems.SNAPDRAGON;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> SNAPDRAGON_SEEDS = ModItems.SNAPDRAGON_SEEDS;
    @Deprecated public static final DeferredItem<Item> VALBERRY = ModItems.VALBERRY;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> VALBERRY_SEEDS = ModItems.VALBERRY_SEEDS;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> DANDELION_SEEDS = ModItems.DANDELION_SEEDS;
    @Deprecated public static final DeferredItem<Item> CECILIA = ModItems.CECILIA;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> CECILIA_SEEDS = ModItems.CECILIA_SEEDS;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> RASPBERRY = ModItems.RASPBERRY;
    @Deprecated public static final DeferredItem<Item> SWEET_FLOWER = ModItems.SWEET_FLOWER;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> SWEET_FLOWER_SEEDS = ModItems.SWEET_FLOWER_SEEDS;
    @Deprecated public static final DeferredItem<Item> JUEYUN_CHILI = ModItems.JUEYUN_CHILI;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> JUEYUN_CHILI_SEEDS = ModItems.JUEYUN_CHILI_SEEDS;
    @Deprecated public static final DeferredItem<Item> GLAZE_LILY = ModItems.GLAZE_LILY;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> GLAZE_LILY_SEEDS = ModItems.GLAZE_LILY_SEEDS;
    @Deprecated public static final DeferredItem<Item> MUFENG_MUSHROOM = ModItems.MUFENG_MUSHROOM;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> MUFENG_MUSHROOM_SPORES = ModItems.MUFENG_MUSHROOM_SPORES;
    @Deprecated public static final DeferredItem<Item> SUMERU_ROSE = ModItems.SUMERU_ROSE;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> SUMERU_ROSE_SEEDS = ModItems.SUMERU_ROSE_SEEDS;
    @Deprecated public static final DeferredItem<Item> GRAINFRUIT = ModItems.GRAINFRUIT;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> GRAINFRUIT_SEEDS = ModItems.GRAINFRUIT_SEEDS;
    @Deprecated public static final DeferredItem<Item> FLUORESCENT_FUNGUS = ModItems.FLUORESCENT_FUNGUS;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> FLUORESCENT_FUNGUS_SPORES = ModItems.FLUORESCENT_FUNGUS_SPORES;
    @Deprecated public static final DeferredItem<Item> SEA_GANODERMA = ModItems.SEA_GANODERMA;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> SEA_GANODERMA_SAMPLE = ModItems.SEA_GANODERMA_SAMPLE;
    @Deprecated public static final DeferredItem<Item> DENDROBIUM = ModItems.DENDROBIUM;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> DENDROBIUM_SEEDS = ModItems.DENDROBIUM_SEEDS;
    @Deprecated public static final DeferredItem<Item> FROSTLAMP_FLOWER = ModItems.FROSTLAMP_FLOWER;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> FROSTLAMP_FLOWER_SEEDS = ModItems.FROSTLAMP_FLOWER_SEEDS;
    @Deprecated public static final DeferredBlock<YunyanCrackleafCropBlock> YUNYAN_LIEYE_CROP = ModBlocks.YUNYAN_LIEYE_CROP;
    @Deprecated public static final DeferredBlock<WildYunyanCrackleafBlock> WILD_YUNYAN_LIEYE = ModBlocks.WILD_YUNYAN_LIEYE;
    @Deprecated public static final DeferredItem<Item> YUNYAN_LIEYE = ModItems.YUNYAN_LIEYE;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> YUNYAN_LIEYE_SEEDS = ModItems.YUNYAN_LIEYE_SEEDS;
    @Deprecated public static final DeferredItem<BlockItem> WILD_YUNYAN_LIEYE_ITEM = ModItems.WILD_YUNYAN_LIEYE_ITEM;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> CORAL_SHELL = ModItems.CORAL_SHELL;
    @Deprecated public static final DeferredItem<Item> CORAL_PEARL = ModItems.CORAL_PEARL;
    @Deprecated public static final DeferredItem<BlockItem> NATURAL_CORAL_PEARL_ITEM = ModItems.NATURAL_CORAL_PEARL_ITEM;
    @Deprecated public static final DeferredItem<Item> HORSETAIL = ModItems.HORSETAIL;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> HORSETAIL_SEEDS = ModItems.HORSETAIL_SEEDS;
    @Deprecated public static final DeferredItem<Item> JINXIN_FLOWER = ModItems.JINXIN_FLOWER;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> JINXIN_FLOWER_BUD = ModItems.JINXIN_FLOWER_BUD;
    @Deprecated public static final DeferredItem<Item> PEPPER = ModItems.PEPPER;
    @Deprecated public static final DeferredItem<Item> SALT = ModItems.SALT;
    @Deprecated public static final DeferredItem<Item> CHENYU_TEA = ModItems.CHENYU_TEA;
    @Deprecated public static final DeferredItem<Item> TOFU = ModItems.TOFU;
    @Deprecated public static final DeferredItem<Item> GLABROUS_BEANS = ModItems.GLABROUS_BEANS;
    @Deprecated public static final DeferredItem<Item> SHRIMP_MEAT = ModItems.SHRIMP_MEAT;
    @Deprecated public static final DeferredItem<Item> ALMOND = ModItems.ALMOND;
    @Deprecated public static final DeferredItem<Item> MATSUTAKE = ModItems.MATSUTAKE;
    @Deprecated public static final DeferredItem<Item> CRAB = ModItems.CRAB;
    @Deprecated public static final DeferredItem<Item> SAUSAGE = ModItems.SAUSAGE;
    @Deprecated public static final DeferredItem<Item> JAM = ModItems.JAM;
    @Deprecated public static final DeferredItem<Item> BUTTER = ModItems.BUTTER;
    @Deprecated public static final DeferredItem<Item> CHEESE = ModItems.CHEESE;
    @Deprecated public static final DeferredItem<Item> CREAM = ModItems.CREAM;
    @Deprecated public static final DeferredItem<Item> SUNSETTIA = ModItems.SUNSETTIA;
    @Deprecated public static final DeferredItem<Item> PINECONE = ModItems.PINECONE;
    @Deprecated public static final DeferredItem<Item> CRAB_ROE = ModItems.CRAB_ROE;
    @Deprecated public static final DeferredItem<Item> SMOKED_FOWL = ModItems.SMOKED_FOWL;
    @Deprecated public static final DeferredItem<Item> MORA = ModItems.MORA;
    @Deprecated public static final DeferredItem<Item> PRIMOGEM = ModItems.PRIMOGEM;
    @Deprecated public static final DeferredItem<BlockItem> PRIMOGEM_BLOCK_ITEM = ModItems.PRIMOGEM_BLOCK_ITEM;
    @Deprecated public static final DeferredItem<BlockItem> MORA_BLOCK_ITEM = ModItems.MORA_BLOCK_ITEM;
    @Deprecated public static final DeferredItem<StarconchItem> STARCONCH_ITEM = ModItems.STARCONCH_ITEM;
    @Deprecated public static final DeferredItem<Item> EMPTY_FEATHER_MOTH_ITEM = ModItems.EMPTY_FEATHER_MOTH_ITEM;
    @Deprecated public static final DeferredItem<DeferredSpawnEggItem> EMPTY_FEATHER_MOTH_SPAWN_EGG = ModItems.EMPTY_FEATHER_MOTH_SPAWN_EGG;
    @Deprecated public static final DeferredItem<DeferredSpawnEggItem> KATHERYNE_SPAWN_EGG = ModItems.KATHERYNE_SPAWN_EGG;
    @Deprecated public static final DeferredItem<KnifeItem> PRIMOGEM_KNIFE = ModItems.PRIMOGEM_KNIFE;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> SHIPO = ModItems.SHIPO;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> JINGHUAGUSUI = ModItems.JINGHUAGUSUI;
    @Deprecated public static final DeferredItem<ItemNameBlockItem> YEBOSHI = ModItems.YEBOSHI;
    @Deprecated public static final DeferredItem<SeedDispensaryItem> SEED_DISPENSARY = ModItems.SEED_DISPENSARY;
    @Deprecated public static final DeferredItem<WindWingsItem> WIND_WINGS = ModItems.WIND_WINGS;
    @Deprecated public static final DeferredItem<PortableNutritionBagItem> PORTABLE_NUTRITION_BAG = ModItems.PORTABLE_NUTRITION_BAG;
    @Deprecated public static final DeferredItem<TeyvatDishItem> TEYVAT_FRIED_EGG = BasicDishes.TEYVAT_FRIED_EGG;
    @Deprecated public static final DeferredItem<TeyvatDishItem> TEYVAT_SCORCHED_EGG = BasicDishes.TEYVAT_SCORCHED_EGG;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MUSHROOM_CHICKEN_SKEWER = BasicDishes.MUSHROOM_CHICKEN_SKEWER;
    @Deprecated public static final DeferredItem<TeyvatDishItem> FRUITY_SKEWERS = BasicDishes.FRUITY_SKEWERS;
    @Deprecated public static final DeferredItem<TeyvatDishItem> GRILLED_STEAK = BasicDishes.GRILLED_STEAK;
    @Deprecated public static final DeferredItem<TeyvatDishItem> OUTRIDERS_CHAMPION_STEAK = BasicDishes.OUTRIDERS_CHAMPION_STEAK;
    @Deprecated public static final DeferredItem<TeyvatDishItem> STIR_FRIED_FILET = BasicDishes.STIR_FRIED_FILET;
    @Deprecated public static final DeferredItem<TeyvatDishItem> RADISH_VEGGIE_SOUP = BasicDishes.RADISH_VEGGIE_SOUP;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MONDSTADT_GRILLED_FISH = BasicDishes.MONDSTADT_GRILLED_FISH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MORA_MEAT = BasicDishes.MORA_MEAT;
    @Deprecated public static final DeferredItem<TeyvatDishItem> LONG_NIGHT_FLAME = BasicDishes.LONG_NIGHT_FLAME;
    @Deprecated public static final DeferredItem<TeyvatDishItem> SMOKED_FISH_STEAK = BasicDishes.SMOKED_FISH_STEAK;
    @Deprecated public static final DeferredItem<TeyvatDishItem> CATCH_OF_THE_DARK_DEPTHS = BasicDishes.CATCH_OF_THE_DARK_DEPTHS;
    @Deprecated public static final DeferredItem<TeyvatDishItem> DARK_EGG = BasicDishes.DARK_EGG;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MINT_SAUCE_GRILLED_FISH = BasicDishes.MINT_SAUCE_GRILLED_FISH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> GRAINFRUIT_CUP = BasicDishes.GRAINFRUIT_CUP;
    @Deprecated public static final DeferredItem<TeyvatDishItem> JADE_PATTERN_TEA_EGG = BasicDishes.JADE_PATTERN_TEA_EGG;
    @Deprecated public static final DeferredItem<PlaceableTeaItem> CHENYU_TEA_BREW = BasicDishes.CHENYU_TEA_BREW;
    @Deprecated public static final DeferredItem<TeyvatDishItem> LEISURE_TEA = BasicDishes.LEISURE_TEA;
    @Deprecated public static final DeferredItem<TeyvatDishItem> HONEY_CHAR_SIU = BasicDishes.HONEY_CHAR_SIU;
    @Deprecated public static final DeferredItem<TeyvatDishItem> ALMOND_TROUT = BasicDishes.ALMOND_TROUT;
    @Deprecated public static final DeferredItem<TeyvatDishItem> CONFIT_DUCK_LEG = BasicDishes.CONFIT_DUCK_LEG;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MINT_BEAN_SOUP = BasicDishes.MINT_BEAN_SOUP;
    @Deprecated public static final DeferredItem<TeyvatDishItem> LAMBAD_FISH_ROLL = BasicDishes.LAMBAD_FISH_ROLL;
    @Deprecated public static final DeferredItem<TeyvatDishItem> WARMTH = BasicDishes.WARMTH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> SOBA_NOODLES = BasicDishes.SOBA_NOODLES;
    @Deprecated public static final DeferredItem<TeyvatDishItem> STRATAGEM = BasicDishes.STRATAGEM;
    @Deprecated public static final DeferredItem<TeyvatDishItem> SATIETY_GEL = BasicDishes.SATIETY_GEL;
    @Deprecated public static final DeferredItem<TeyvatDishItem> ETERNAL_FAITH = BasicDishes.ETERNAL_FAITH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> BIRD_EGG_YAKI = BasicDishes.BIRD_EGG_YAKI;
    @Deprecated public static final DeferredItem<TeyvatDishItem> BIRD_EGG_SUSHI = BasicDishes.BIRD_EGG_SUSHI;
    @Deprecated public static final DeferredItem<TeyvatDishItem> SWEET_SHRIMP_SUSHI = BasicDishes.SWEET_SHRIMP_SUSHI;
    @Deprecated public static final DeferredItem<TeyvatDishItem> RAIN_OR_SHINE = BasicDishes.RAIN_OR_SHINE;
    @Deprecated public static final DeferredItem<TeyvatDishItem> DRY_BRAISED_FISH = BasicDishes.DRY_BRAISED_FISH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MISO_SOUP = BasicDishes.MISO_SOUP;
    @Deprecated public static final DeferredItem<TeyvatDishItem> RICE_BUNS = BasicDishes.RICE_BUNS;
    @Deprecated public static final DeferredItem<TeyvatDishItem> MINT_JELLY = BasicDishes.MINT_JELLY;
    @Deprecated public static final DeferredItem<TeyvatDishItem> DEFINITELY_NOT_BAR_FOOD = BasicDishes.DEFINITELY_NOT_BAR_FOOD;
    @Deprecated public static final DeferredItem<TeyvatDishItem> QIANKUN_MORA_MEAT = BasicDishes.QIANKUN_MORA_MEAT;
    @Deprecated public static final DeferredItem<TeyvatDishItem> GRILLED_TIGER_FISH = BasicDishes.GRILLED_TIGER_FISH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> LARGE_BOWL_OF_TEA = BasicDishes.LARGE_BOWL_OF_TEA;
    @Deprecated public static final DeferredItem<TeyvatDishItem> FLAMING_STIR_FRIED_FILET = BasicDishes.FLAMING_STIR_FRIED_FILET;
    @Deprecated public static final DeferredItem<TeyvatDishItem> SURVIVAL_GRILLED_FISH = BasicDishes.SURVIVAL_GRILLED_FISH;
    @Deprecated public static final DeferredItem<TeyvatDishItem> XIAN_TIAO_QIANG = BasicDishes.XIAN_TIAO_QIANG;
    @Deprecated public static final DeferredItem<TeyvatDishItem> OLD_COURTYARD_SMOKED_SAUSAGE = BasicDishes.OLD_COURTYARD_SMOKED_SAUSAGE;
    @Deprecated public static final DeferredHolder<CreativeModeTab, CreativeModeTab> TEYVAT_DELIGHT_TAB = ModCreativeTabs.TEYVAT_DELIGHT_TAB;

    public TeyvatDelight(IEventBus modEventBus, ModContainer modContainer) {
        KatheryneShopConfig.initialize(net.neoforged.fml.loading.FMLPaths.CONFIGDIR.get());
        modContainer.registerConfig(ModConfig.Type.COMMON, TeyvatDelightConfig.SPEC);
        KatheryneNetwork.register(modEventBus);
        NutritionBagNetwork.register(modEventBus);
        ModRegistries.register(modEventBus);
        ModEvents.register();
        if (ModList.get().isLoaded("curios") && ModList.get().isLoaded("caelus")) {
            modEventBus.addListener(WindWingsCurios::register);
        }
    }
}
